# Generated by Django 2.2.3 on 2019-09-10 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoSeguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'EquipoSeguridad',
            },
        ),
        migrations.CreateModel(
            name='EquiposporInvitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Security Equipment by Invitation',
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_envio', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_hora_invitacion', models.DateTimeField()),
                ('asunto', models.CharField(max_length=254)),
                ('automovil', models.BooleanField()),
                ('notas', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('empresa', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('qr_code', models.CharField(blank=True, max_length=16, unique=True)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Area')),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empleado')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_company_inv', to='Empresas.Empresa')),
            ],
            options={
                'verbose_name_plural': 'INVITACIONES',
            },
        ),
        migrations.CreateModel(
            name='InvitacionReferido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTercero', models.EmailField(max_length=254)),
                ('asignada', models.BooleanField(default=False)),
                ('hashCode', models.CharField(max_length=100, unique=True)),
                ('idInvitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.Invitacion')),
            ],
            options={
                'verbose_name_plural': 'InvitacionesReferido',
            },
        ),
    ]
