# Generated by Django 2.2 on 2019-05-02 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_auto_20190502_1331'),
        ('Invitaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionempresarial',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='id_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Area'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empleado'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empresa'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equiposporinvitacion',
            name='id_equipo_seguridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.EquipoSeguridad'),
        ),
        migrations.AddField(
            model_name='equiposporinvitacion',
            name='id_invitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.Invitacion'),
        ),
        migrations.AddField(
            model_name='equipoporinvitaciontemporal',
            name='id_equipo_seguridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.EquipoSeguridad'),
        ),
        migrations.AddField(
            model_name='equipoporinvitaciontemporal',
            name='id_invitacion_temporal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.InvitacionTemporal'),
        ),
        migrations.AddField(
            model_name='equipoporinvitacionesempresariales',
            name='id_equipo_seguridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.EquipoSeguridad'),
        ),
        migrations.AddField(
            model_name='equipoporinvitacionesempresariales',
            name='id_invitacion_empresarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.InvitacionEmpresarial'),
        ),
    ]
