# Generated by Django 2.2.4 on 2019-08-14 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Invitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='id_usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equiposporinvitacion',
            name='id_equipo_seguridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.EquipoSeguridad'),
        ),
        migrations.AddField(
            model_name='equiposporinvitacion',
            name='id_invitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.Invitacion'),
        ),
    ]
