# Generated by Django 2.2.3 on 2019-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0002_auto_20190910_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='notas',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
