# Generated by Django 2.2.3 on 2019-10-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0002_auto_20191018_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='Token',
            field=models.CharField(default='03bd5e57d47733', max_length=14),
        ),
    ]
