# Generated by Django 2.2.3 on 2019-10-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0002_auto_20191009_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='referredPhone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
