# Generated by Django 2.2.3 on 2019-09-30 00:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0002_auto_20190929_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.datetime(2019, 10, 1, 0, 5, 27, 584632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 0, 5, 27, 584632, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_hora_envio',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 0, 5, 27, 584632, tzinfo=utc)),
        ),
    ]
