# Generated by Django 2.2.3 on 2019-10-15 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0002_auto_20191014_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 10, 16)),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='Token',
            field=models.CharField(default='da8e5ff7ea93a8', max_length=14),
        ),
    ]
