# Generated by Django 2.2.3 on 2019-09-25 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0002_auto_20190924_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_hora_envio',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 23, 0, 35, 55653, tzinfo=utc)),
        ),
    ]
