# Generated by Django 2.2.3 on 2019-10-24 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0002_auto_20191021_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 10, 25)),
        ),
    ]
