# Generated by Django 2.2.3 on 2019-10-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20191020_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitacion',
            name='urlVideo',
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='Token',
            field=models.CharField(default='e3d86faa9324a6', max_length=14),
        ),
    ]
