# Generated by Django 2.2.3 on 2019-09-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20190925_1800'),
        ('Invitaciones', '0003_auto_20190925_1759'),
    ]

    operations = [
    ]
