# Generated by Django 2.2.3 on 2019-10-28 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20191024_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitacion',
            old_name='leida',
            new_name='confirmed',
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 10, 29)),
        ),
    ]
