# Generated by Django 2.2.3 on 2019-09-18 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20190917_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitacion',
            name='fecha_hora_invitacion',
        ),
        migrations.AddField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.date(2000, 9, 18)),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='diary',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2000, 9, 18), null=True),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='timeInv',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='typeInv',
            field=models.IntegerField(default=0),
        ),
    ]
