# Generated by Django 2.2.3 on 2019-10-15 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20191015_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='referredinvitation',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 10, 16)),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='Token',
            field=models.CharField(default='8e69f8cd560345', max_length=14),
        ),
    ]
