# Generated by Django 2.2.3 on 2019-09-30 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20190925_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.datetime(2019, 10, 1, 2, 46, 29, 678601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2019, 10, 3, 2, 46, 29, 678601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_hora_envio',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 2, 46, 29, 678601, tzinfo=utc)),
        ),
    ]
