# Generated by Django 2.2.3 on 2019-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20190930_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationbyusers',
            name='qr_code',
            field=models.CharField(max_length=30),
        ),
    ]
