# Generated by Django 2.2.3 on 2019-10-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0004_auto_20191001_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitacion',
            name='qr_code',
        ),
    ]
