# Generated by Django 2.2.3 on 2019-09-18 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0004_auto_20190918_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 9, 19), null=True),
        ),
    ]
