# Generated by Django 2.2.3 on 2019-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0004_auto_20191010_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='qrCode',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='referredMail',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='referredPhone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
