# Generated by Django 2.2.3 on 2019-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0004_auto_20191020_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='urlVideo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='Token',
            field=models.CharField(default='77b008ab8c0396', max_length=14),
        ),
    ]
