# Generated by Django 2.2.3 on 2019-10-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0004_auto_20191028_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitacion',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='invitationbyusers',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
