# Generated by Django 2.2.3 on 2019-10-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0004_auto_20191015_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='Token',
            field=models.CharField(default='af094a71b5316a', max_length=14),
        ),
    ]
