# Generated by Django 2.2.3 on 2019-10-30 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0005_auto_20191028_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 10, 31)),
        ),
    ]
