# Generated by Django 2.2.3 on 2019-09-18 22:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0005_auto_20190918_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 9, 19)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_hora_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
