# Generated by Django 2.2.3 on 2019-10-16 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0006_auto_20191015_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referredinvitation',
            old_name='id_area',
            new_name='areaId',
        ),
        migrations.RenameField(
            model_name='referredinvitation',
            old_name='empresa',
            new_name='companyFrom',
        ),
        migrations.RenameField(
            model_name='referredinvitation',
            old_name='notas',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='referredinvitation',
            old_name='asunto',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='referredinvitation',
            old_name='automovil',
            new_name='vehicle',
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 10, 17)),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='Token',
            field=models.CharField(default='2c0cb3412bdaea', max_length=14),
        ),
        migrations.AlterField(
            model_name='referredinvitation',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 10, 17)),
        ),
    ]
