# Generated by Django 2.2.3 on 2019-12-18 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0007_auto_20191105_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 12, 19)),
        ),
    ]
