# Generated by Django 2.2.3 on 2019-09-19 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0007_auto_20190918_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.date(2019, 9, 20)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 9, 21)),
        ),
    ]
