# Generated by Django 2.2.3 on 2019-09-20 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0008_auto_20190919_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.date(2019, 9, 21)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 9, 23)),
        ),
    ]
