# Generated by Django 2.2.3 on 2020-01-09 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0008_auto_20191218_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredinvitation',
            name='expiration',
            field=models.DateField(default=datetime.date(2020, 1, 10)),
        ),
    ]
