# Generated by Django 2.2.3 on 2019-09-21 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0009_auto_20190919_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.date(2019, 9, 22)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=datetime.date(2019, 9, 24)),
        ),
    ]
