# Generated by Django 2.2.3 on 2019-09-21 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0010_auto_20190921_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=models.DateField(default=datetime.date(2019, 9, 22))),
        ),
    ]
