# Generated by Django 2.2.3 on 2019-09-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0002_auto_20190910_1517'),
        ('Invitaciones', '0011_auto_20190921_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='id_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresas.Administrador'),
        ),
    ]
