# Generated by Django 2.2.3 on 2019-09-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0013_auto_20190923_1112'),
        ('Invitaciones', '0010_auto_20190923_1524'),
    ]

    operations = [
    ]
