# Generated by Django 2.2.3 on 2019-09-24 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0014_merge_20190923_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.date(2019, 9, 25)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=models.DateField(default=datetime.date(2019, 9, 25))),
        ),
    ]
