# Generated by Django 2.2.3 on 2019-09-25 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0015_auto_20190923_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='dateInv',
            field=models.DateField(default=datetime.date(2019, 9, 26)),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='expiration',
            field=models.DateField(default=models.DateField(default=datetime.date(2019, 9, 26))),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_hora_envio',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 1, 9, 27, 870127, tzinfo=utc)),
        ),
    ]
