# Generated by Django 2.2.3 on 2019-09-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temporalToken',
            field=models.CharField(blank=True, default='', max_length=5, unique=True),
        ),
    ]
