# Generated by Django 2.2.3 on 2019-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_customuser_temporaltoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='temporalToken',
            field=models.CharField(blank=True, default='', max_length=6, unique=True),
        ),
    ]
