# Generated by Django 2.2.3 on 2019-10-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20191024_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='temporalToken',
            field=models.CharField(blank=True, default='3474389954', max_length=10, null=True),
        ),
    ]
