# Generated by Django 2.2.3 on 2019-10-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20191028_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='temporalToken',
            field=models.CharField(blank=True, default='6146844262', max_length=10, null=True),
        ),
    ]
