# Generated by Django 2.2.3 on 2019-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20191030_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='temporalToken',
            field=models.CharField(blank=True, default='9841159860', max_length=10, null=True),
        ),
    ]
