# Generated by Django 2.2.3 on 2019-09-18 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20190911_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anfitrion', to=settings.AUTH_USER_MODEL),
        ),
    ]
