# Generated by Django 2.2.3 on 2019-09-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_customuser_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canSendSmS', models.BooleanField(default=True)),
                ('canSendEmail', models.BooleanField(default=True)),
                ('language', models.CharField(default='esp', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='userSettings',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.UserSettings'),
        ),
    ]
