# Generated by Django 2.2.3 on 2019-09-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_auto_20190919_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userSettings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.UserSettings'),
            preserve_default=False,
        ),
    ]
