# Generated by Django 2.2.3 on 2019-09-19 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_auto_20190919_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userSettings',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anfitrion', to=settings.AUTH_USER_MODEL),
        ),
    ]
