# Generated by Django 2.2.3 on 2019-09-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_has_contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.Contacto')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.Grupo')),
            ],
        ),
    ]
