# Generated by Django 2.2.3 on 2019-10-10 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_auto_20191009_2009'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_has_contacto',
            name='id_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo_has_contacto',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.Grupo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empleado'),
        ),
    ]
