# Generated by Django 2.2.3 on 2019-10-18 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grupos', '0002_auto_20191014_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='id_empleado',
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
