# Generated by Django 2.2 on 2019-05-02 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invitaciones', '0001_initial'),
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Parques',
            },
        ),
        migrations.CreateModel(
            name='VigilanteParque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('activo', models.BooleanField()),
                ('id_parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parques.Parque')),
            ],
            options={
                'verbose_name_plural': 'Vigilantes del Parque',
            },
        ),
        migrations.CreateModel(
            name='AccesoParque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_acceso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_Salida', models.DateTimeField(auto_now=True)),
                ('comentarios', models.CharField(max_length=45)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empresa')),
                ('id_invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.Invitacion')),
                ('id_parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parques.Parque')),
            ],
            options={
                'verbose_name_plural': 'Accesos al Parque',
            },
        ),
    ]
