# Generated by Django 2.2 on 2019-05-02 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_auto_20190502_1331'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Parques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoparque',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesoparque',
            name='id_vigilante_parqueEnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_entrada', to='Empresas.Vigilante'),
        ),
        migrations.AddField(
            model_name='accesoparque',
            name='id_vigilante_parqueSal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_salida', to='Empresas.Vigilante'),
        ),
    ]
