# Generated by Django 2.2 on 2019-05-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_auto_20190502_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_acceso', models.DateTimeField()),
                ('f_salida', models.DateTimeField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empleado')),
                ('id_emprea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empresa')),
                ('id_vigilante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Vigilante')),
            ],
            options={
                'verbose_name_plural': 'Bitacoras Empresariales',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_acceso', models.DateTimeField()),
                ('f_salida', models.DateTimeField()),
                ('url_foto', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=100)),
                ('notas', models.TextField()),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Area')),
                ('id_caseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Caseta')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empleado')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Empresa')),
                ('id_vigilante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empresas.Vigilante')),
            ],
        ),
    ]
