# Generated by Django 2.2.3 on 2019-09-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_acceso', models.DateTimeField()),
                ('f_salida', models.DateTimeField()),
                ('url_foto', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=100)),
                ('notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_acceso', models.DateTimeField()),
                ('f_salida', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Bitacoras Empresariales',
            },
        ),
    ]
