# Generated by Django 2.2.3 on 2019-09-18 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacoras', '0003_auto_20190918_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='f_acceso',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
