# Generated by Django 2.2.3 on 2019-09-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacoras', '0004_auto_20190918_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='f_salida',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
