# Generated by Django 2.2.3 on 2019-09-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bitacoras', '0005_auto_20190918_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='url_foto',
            field=models.ImageField(default=None, max_length=256, upload_to='WithoutAccess'),
        ),
    ]
