"""
Django settings for ControlAccs project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import enum
import nexmo


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES_DIR = BASE_DIR.join('templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q1!a)g2djh=pw^v$()_!cf0m1ijwbk&(y*yd8kqzxe0enne-y!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'intrare-services.com'] 
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# Aquí le decimos a django que utilice nuestra clase de user tuneada xD
AUTH_USER_MODEL = 'Usuarios.CustomUser'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        #'rest_framework.authentication.BasicAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

ORGANIZATIONNAME = 'EDISON EFFECT SA DE CV'
PASSTYPEIDENTIFIER = 'pass.com.daelabs.intrare.mx'
TEAMIDENTIFIER = '6VAW5LY4HJ'
WALLETPASS = 'mientras123'
CRD = os.path.join(BASE_DIR, 'certf')

DJOSER = {
    'SERIALIZERS': {
         'user': 'Usuarios.serializers.UserSerializer'
    },
    'PERMISSIONS': {
         'user': ('Usuarios.permissions.IsGetRequest',),
    }
}

NONE = 0
EMPLEADO = 1
VIGILANTE = 2
PAR_VIGILANTE = 3
ADMIN_PARQUE = 4
ADMIN = 5

#Config Email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'rstestmx@gmail.com'
EMAIL_HOST_PASSWORD = 'mientras123'


FCM_DJANGO_SETTINGS = {
        "APP_VERBOSE_NAME": "intrarebeta",
         # default: _('FCM Django')
        "FCM_SERVER_KEY": "AAAA2tW-hz8:APA91bFe0xRV-wdUeTR6dcmoplFDD-TGsVw63ikoGTKz3ip2oh25h2_Apj8-1-1-dNnth08D1pGibqCgerRDtDZm0NQfi1ICaGadpN-MoIrS8KAmBNfqORFgC9Wti0Vdtjn3HYjDHaUB",
         # true if you want to have only one active device per registered user at a time
         # default: False
        "ONE_DEVICE_PER_USER": False,
         # devices to which notifications cannot be sent,
         # are deleted upon receiving error response from FCM
         # default: False
        "DELETE_INACTIVE_DEVICES": False,
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',

    'Wallet',

    'django_filters',

    'rest_framework',
    'rest_framework.authtoken',  # Token Authentication.
    # App Para con control de los usuarios (Login, Registro, Token, Email, Etc)..
    # https://djoser.readthedocs.io/en/latest/
    'djoser',
    'fcm_django',

    'Usuarios',
    'Empresas.apps.EmpresasConfig',
    'Invitaciones.apps.InvitacionesConfig',
    'Parques.apps.ParquesConfig',
    'Bitacoras.apps.BitacorasConfig',
    'Grupos.apps.GruposConfig',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


CORS_ORIGIN_WHITELIST = (
    'http://localhost:8000',
)
CORS_ORIGIN_REGEX_WHITELIST = (
    'http://localhost:8000',
)


ROOT_URLCONF = 'ControlAccs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ControlAccs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'IntrareEmpresa',
        'USER': 'blame711019',
        'PASSWORD': 'HIPIcc711019',
        'HOST': 'intrare-freetierdb.c8dwggxf5yjq.us-east-2.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT= os.path.join(BASE_DIR, 'static/')
#
# MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AWS_ACCESS_KEY_ID = 'AKIAVZH4SBSY373JN77R'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'bucketeer-576c8228-7737-4878-8397-1c8403d07005'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
