# Generated by Django 2.2.3 on 2019-10-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invitaciones', '0003_auto_20190930_1721'),
        ('Empresas', '0002_auto_20190930_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='id_invitacion',
        ),
        migrations.AddField(
            model_name='acceso',
            name='invitationByUsers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Invitaciones.InvitationByUsers'),
            preserve_default=False,
        ),
    ]
