# Generated by Django 2.2.3 on 2019-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0002_auto_20190924_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default=None, max_length=256, upload_to='Logos'),
        ),
    ]
