# Generated by Django 2.2.3 on 2019-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0003_auto_20191030_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puede_enviar',
            field=models.BooleanField(default=True),
        ),
    ]
