# Generated by Django 2.2.3 on 2019-10-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0003_auto_20191001_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='qr_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
