# Generated by Django 2.2.3 on 2019-10-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0003_auto_20191018_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityequipment',
            name='nameEquipment',
            field=models.CharField(max_length=254),
        ),
    ]
