# Generated by Django 2.2.3 on 2019-11-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0004_auto_20191030_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Employee'},
        ),
    ]
