# Generated by Django 2.2.3 on 2019-12-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0005_auto_20191105_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
